name: sagestone_flutter
description: Flutter product app for SageStone Email Marketing
version: 0.1.0

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod: ^2.4.0
  freezed_annotation: ^2.4.1
  dio: ^5.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  freezed: ^2.4.1
  build_runner: ^2.4.6
